IB_EMPLOY_STAT_EMPLOYED = 0
IB_EMPLOY_STAT_UNEMPLOYED = 1
IB_EMPLOY_STAT_SELF_EMPLOYED = 2
IB_EMPLOY_STAT_RETIRED = 3
IB_EMPLOY_STAT_HOMEMAKER = 4
IB_EMPLOY_STAT_AT_HOME_TRADER = 5
IB_EMPLOY_STAT_STUDENT = 6

IB_EMPLOY_STATUSES = (
    (IB_EMPLOY_STAT_EMPLOYED, 'EMPLOYED'),
    (IB_EMPLOY_STAT_UNEMPLOYED, 'UNEMPLOYED'),
    (IB_EMPLOY_STAT_SELF_EMPLOYED, 'SELFEMPLOYED'),
    (IB_EMPLOY_STAT_RETIRED, 'RETIRED'),
    (IB_EMPLOY_STAT_HOMEMAKER, 'HOMEMAKER'),
    (IB_EMPLOY_STAT_AT_HOME_TRADER, 'ATHOMETRADER'),
    (IB_EMPLOY_STAT_STUDENT, 'STUDENT'),
)

SOURCE_OF_FUNDS_TYPE_CONSULTING = 0
SOURCE_OF_FUNDS_TYPE_DISABILITY = 1
SOURCE_OF_FUNDS_TYPE_INHERITANCE = 2
SOURCE_OF_FUNDS_TYPE_INTEREST = 3
SOURCE_OF_FUNDS_TYPE_REAL_ESTATE = 4
SOURCE_OF_FUNDS_TYPE_RENTAL = 5
SOURCE_OF_FUNDS_TYPE_SEVERANCE = 6
SOURCE_OF_FUNDS_TYPE_SPOUSE = 7
SOURCE_OF_FUNDS_TYPE_TRADING_AND_INVESTMENTS = 8
SOURCE_OF_FUNDS_TYPE_UNEMPLOYMENT = 9
SOURCE_OF_FUNDS_TYPE_OTHER = 10

SOURCE_OF_FUNDS_TYPES = (
    (SOURCE_OF_FUNDS_TYPE_CONSULTING, 'Consulting'),
    (SOURCE_OF_FUNDS_TYPE_DISABILITY, 'Disability'),
    (SOURCE_OF_FUNDS_TYPE_INHERITANCE, 'Inheritance'),
    (SOURCE_OF_FUNDS_TYPE_INTEREST, 'Interest'),
    (SOURCE_OF_FUNDS_TYPE_REAL_ESTATE, 'Real Estate'),
    (SOURCE_OF_FUNDS_TYPE_RENTAL, 'Rental'),
    (SOURCE_OF_FUNDS_TYPE_SEVERANCE, 'Severance'),
    (SOURCE_OF_FUNDS_TYPE_SPOUSE, 'Spouse'),
    (SOURCE_OF_FUNDS_TYPE_TRADING_AND_INVESTMENTS, 'Trading and Investments'),
    (SOURCE_OF_FUNDS_TYPE_UNEMPLOYMENT, 'Unemployment'),
    (SOURCE_OF_FUNDS_TYPE_OTHER, 'Other'),
)

IB_SALUTATION_MR = 'Mr.'
IB_SALUTATION_MRS = 'Mrs.'
IB_SALUTATION_MS = 'Ms.'
IB_SALUTATION_DR = 'Dr.'

IB_SALUTATION_CHOICES = (
    (IB_SALUTATION_MR, IB_SALUTATION_MR),
    (IB_SALUTATION_MRS, IB_SALUTATION_MRS),
    (IB_SALUTATION_MS, IB_SALUTATION_MS),
    (IB_SALUTATION_DR, IB_SALUTATION_DR),
)

IB_SUFFIX_SR = 'Sr.'
IB_SUFFIX_JR = 'Jr.'
IB_SUFFIX_I = 'I'
IB_SUFFIX_II = 'II'
IB_SUFFIX_III = 'III'
IB_SUFFIX_IV = 'IV'
IB_SUFFIX_V = 'V'

IB_SUFFIX_CHOICES = (
    (IB_SUFFIX_SR, IB_SUFFIX_SR),
    (IB_SUFFIX_JR, IB_SUFFIX_JR),
    (IB_SUFFIX_I, IB_SUFFIX_I),
    (IB_SUFFIX_II, IB_SUFFIX_II),
    (IB_SUFFIX_III, IB_SUFFIX_III),
    (IB_SUFFIX_IV, IB_SUFFIX_IV),
    (IB_SUFFIX_V, IB_SUFFIX_V),
)
