from django.apps import apps
from django.utils import six
from pinax.eventlog.models import log as event_log

from common.structures import ChoiceEnum


class InvalidLogParams(Exception):
    def __init__(self, event, args):
        self.event = event
        self.args = args

    def __str__(self):
        return ("Invalid arguments passed to log() for event: {}. "
                "Required: {}, got: {}".format(self.event, self.event.log_keys,
                                               self.args))


class Event(ChoiceEnum):
    """
    The ordering of the numbers here is not important, their uniqueness will
     be ensured by the enum.
    Group the values as desired (maybe by function, or alphabetically
    """
    # Format: (id, list_of_event_logging_data, required object type)
    PLACE_MARKET_ORDER = (0, ['order'], 'client.ClientAccount')
    CANCEL_MARKET_ORDER = (1, [], 'client.ClientAccount')
    ARCHIVE_GOAL_REQUESTED = (2, [], 'goal.Goal')
    ARCHIVE_GOAL = (3, [], 'goal.Goal')
    REACTIVATE_GOAL = (4, [], 'goal.Goal')
    # "Settings changes approved"
    APPROVE_SELECTED_SETTINGS = (5, [], 'goal.Goal')
    # "Settings changes reverted"
    REVERT_SELECTED_SETTINGS = (6, [], 'goal.Goal')
    # "Settings update '{}' requested"
    SET_SELECTED_SETTINGS = (7, ['request'], 'goal.Goal')
    # "Settings change '{}' requested"
    UPDATE_SELECTED_SETTINGS = (8, ['request'], 'goal.Goal')
    # "Withdrawal from goal requested"
    GOAL_WITHDRAWAL = (9, ['request'], 'goal.Goal')
    # "Deposit to goal requested"
    GOAL_DEPOSIT = (10, ['request'], 'goal.Goal')

    # We may never actually log the below, as we have the data stored in
    # the HistoricalBalance table.
    # It's here so we can easily process it for the account activity endpoint.
    GOAL_BALANCE_CALCULATED = (11, [], 'goal.Goal')

    # Events listed in the Transaction.EXECUTION_EVENTS get a 'transaction'
    # field populated in the 'extra' field when viewing the event activity.
    GOAL_WITHDRAWAL_EXECUTED = (12, ['txid'], 'goal.Goal')
    GOAL_DEPOSIT_EXECUTED = (13, ['txid'], 'goal.Goal')
    GOAL_DIVIDEND_DISTRIBUTION = (14, ['txid'], 'goal.Goal')
    GOAL_FEE_LEVIED = (15, ['txid', 'cause'], 'goal.Goal')
    GOAL_REBALANCE_EXECUTED = (16, ['txid'], 'goal.Goal')
    GOAL_TRANSFER_EXECUTED = (17, ['txid'], 'goal.Goal')
    GOAL_ORDER_DISTRIBUTION = (18, ['txid'], 'goal.Goal')

    # RetirementAdvice Events
    RETIRESMARTZ_PROTECTIVE_MOVE = (19, ['prev_risk', 'new_risk'], 'retiresmartz.RetirementPlan')
    RETIRESMARTZ_DYNAMIC_MOVE = (20, ['prev_risk', 'new_risk'], 'retiresmartz.RetirementPlan')
    RETIRESMARTZ_SPENDING_UP_CONTRIB_DOWN = (21, ['prev_btc', 'new_btc'], 'retiresmartz.RetirementPlan')
    RETIRESMARTZ_SPENDING_DOWN_CONTRIB_UP = (22, ['prev_btc', 'new_btc'], 'retiresmartz.RetirementPlan')

    RETIRESMARTZ_RETIREMENT_AGE_ADJUSTED = (23, ['prev_age', 'new_age'], 'retiresmartz.RetirementPlan')

    RETIRESMARTZ_IS_A_SMOKER = (24, [], 'client.Client')
    RETIRESMARTZ_IS_NOT_A_SMOKER = (25, [], 'client.Client')
    RETIRESMARTZ_EXERCISE_ONLY = (26, [], 'client.Client')
    RETIRESMARTZ_WEIGHT_AND_HEIGHT_ONLY = (27, [], 'client.Client')
    RETIRESMARTZ_COMBINATION_WELLBEING_ENTRIES = (28, [], 'client.Client')
    RETIRESMARTZ_ALL_WELLBEING_ENTRIES = (29, [], 'client.Client')

    RETIRESMARTZ_ON_TRACK_NOW = (30, [], 'retiresmartz.RetirementPlan')
    RETIRESMARTZ_OFF_TRACK_NOW = (31, [], 'retiresmartz.RetirementPlan')

    RETIRESMARTZ_SPENDING_UP_CONTRIB_DOWN_AGAIN = (32, ['prev_btc', 'new_btc'], 'retiresmartz.RetirementPlan')

    RETIRESMARTZ_DRINKS_MORE_THAN_ONE = (33, [], 'client.Client')
    RETIRESMARTZ_DRINKS_ONE_OR_LESS = (34, [], 'client.Client')

    # TODO: Update `list_of_event_logging_data` & `required object type` below.

    # Documents Type: `Statements of Advice`
    SOA_GENERATED = (50, [], 'statements.StatementOfAdvice')

    # Documents Type: `Records of Advice`
    ROA_GENERATED = (51, [], 'statements.RecordOfAdvice')

    # Documents Type: `Retirement Statement of Advice`
    RETIREMENT_SOA_GENERATED = (52, [], 'statements.RetirementStatementOfAdvice')

    # ONLY CONFIRMED ALLOCATION CHANGES
    ALLOCATION_CHANGED = (53, [], 'goal.Goal')

    # when a tax loss harvest occurs, it should auto-generate a report
    TAX_LOSS_HARVESTED = (54, [], 'goal.Goal')

    # annual/quarterly statements to be generated by system
    STATEMENTS_GENERATED = (55, [], 'goal.Goal')

    # annual tax forms to be generated by system
    TAX_FORMS_GENERATED = (56, [], 'goal.Goal')

    # Other - any other documents/letters issued to the client by admin/advisor/firm
    OTHERS_GENERATED = (57, [], 'goal.Goal')

    def __init__(self, id, log_keys, obj_class: str):
        """
        Create an Event enumeration.
        This is overridden to have all the extra data we want.

        :param obj_class: What is the required class of the obj logged?
        """
        if 'reason' in log_keys:
            raise ValueError("'reason' is a reserved event logging key. Maybe "
                             "you should use the 'reason' argument to the "
                             "'Event.log' method instead?")
        self.log_keys = log_keys
        self._obj_class = obj_class

    @property
    def obj_class(self):
        if isinstance(self._obj_class, six.string_types):
            app_label, model_name = self._obj_class.rsplit('.', 1)
            self._obj_class = apps.get_model(app_label, model_name)
        return self._obj_class

    def log(self, reason, *args, user=None, obj=None, support_request_id=None):
        """
        Log the event to the event log
        :param reason: The reason this event occurred. The cause of the event.
        :param args:
            The arguments appropriate for the particular event.
            All are required and positional.
            repr() will be called on each argument before logging.
        :param user: The user performing the event
        :param obj: The object the event concerns.
                    Objects of a ClientAccount type will show up on
                        the account activity stream.
                    Objects of a Goal type will show up on the goal and
                        account activity streams.
        :param support_request_id: if this action's been performed by support
                                request
        :return: The event that was logged.
        """
        if not isinstance(obj, self.obj_class):
            raise TypeError("obj parameter: {} is not of required type: {}"
                            .format(type(obj), self.obj_class))

        if len(args) != len(self.log_keys):
            raise InvalidLogParams(self, args)

        log_data = dict(zip(self.log_keys, map(repr, args)))
        log_data['reason'] = reason
        if support_request_id:
            log_data['support_request_id'] = support_request_id
        return event_log(user, self.name, log_data, obj=obj)
